// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const counter: string;
export const counterDecrement: string;
export const count: string;
export const counterIncrement: string;
