// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const events: string;
export const event: string;
export const eventTimeText: string;
export const eventSeparator: string;
export const eventName: string;
export const eventNameText: string;
export const pagination: string;
