// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const difficulty: string;
export const difficultyLabel: string;
export const details: string;
export const detailsList: string;
export const detailsListTerm: string;
export const detailsListDescription: string;
export const detailsMap: string;
export const detailsMapFrame: string;
export const description: string;
export const pagination: string;
