// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const shopProduct: string;
export const shopProductImages: string;
export const shopProductImage: string;
export const shopProductDetails: string;
