// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const shopProduct: string;
export const shopProductImages: string;
export const shopProductImage: string;
export const shopProductDetails: string;
export const sizeLabel: string;
export const sizes: string;
export const size: string;
export const isSelected: string;
export const discounts: string;
export const discountsSelect: string;
