// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const item: string;
export const itemImages: string;
export const itemImage: string;
export const itemDetails: string;
