// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const button: string;
export const isAccent1: string;
export const isAccent2: string;
export const isAccent3: string;
export const buttonBanner: string;
export const buttonBannerText: string;
export const buttonLabel: string;
export const buttonLabelText: string;
export const isSmall: string;
export const isLarge: string;
export const isDisabled: string;
