// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const content: string;
export const header: string;
export const headerContent: string;
export const headerLogo: string;
export const mobileMenu: string;
export const main: string;
export const mobileNav: string;
export const mobileNavClose: string;
export const desktopNav: string;
