// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const cart: string;
export const cartItems: string;
export const cartItemImage: string;
export const cartItemDetails: string;
export const summary: string;
export const total: string;
export const paypal: string;
