// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const indexLogo: string;
export const indexDate: string;
export const indexMenu: string;
