// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const form: string;
export const label: string;
export const labelLabel: string;
export const isRequired: string;
export const footer: string;
export const footerRight: string;
