// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const shopItems: string;
export const shopItemLink: string;
export const shopItemImage: string;
