// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const sponsorsGrid: string;
export const sponsorsGridPresenting: string;
export const sponsorsGridSupporting: string;
export const sponsorsIntro: string;
export const sponsorsSponsor: string;
export const sponsorsSponsorLogo: string;
