// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const description: string;
export const sponsors: string;
export const isPresenting: string;
export const isSupporting: string;
export const sponsor: string;
export const sponsorLogo: string;
