// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const button: string;
export const buttonOrangeColor: string;
export const buttonBlueColor: string;
export const buttonGreenColor: string;
export const buttonBanner: string;
export const buttonContent: string;
export const buttonLarge: string;
