// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const button: string;
export const isOrangeColor: string;
export const isBlueColor: string;
export const isGreenColor: string;
export const buttonBanner: string;
export const buttonLabel: string;
export const isLarge: string;
