// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const content: string;
export const header: string;
export const headerContent: string;
export const headerLogo: string;
export const headerNav: string;
export const headerNavItem: string;
export const main: string;
