// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const layoutContent: string;
export const layoutHeader: string;
export const layoutHeaderContent: string;
export const layoutHeaderLogo: string;
export const layoutHeaderNav: string;
export const layoutHeaderNavItem: string;
export const layoutMain: string;
