// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navigation: string;
export const previous: string;
export const next: string;
export const label: string;
